### ISSUE TITLE
No longer litsens to messages.

### ISSUE THREAD

**Issue by RogthatSinatra** [bruno222/whatsapp-web-bot#24] opened 2018-02-12 06:48 UTC
New messages cannot be read.
console only shows nothing to do.

**Comment by valenti1234** [comment] 2018-02-12 14:44
same problem here, whatsapp release a new version that cheange everything

**Comment by Julian1104** [comment] 2018-02-14 17:05
no work!

**Comment by NelsonGaldeman** [comment] 2018-02-14 18:16
It seems that WhatsApp obfuscated class names because of this kind of bots... I will check if I can do something later.

![imagen](https://user-images.githubusercontent.com/9610178/36220551-c6f09a28-1199-11e8-88d3-2af4c4435e50.png)

**Comment by NelsonGaldeman** [comment] 2018-02-14 18:18
Duplicate of https://github.com/bruno222/whatsapp-web-bot/issues/22

**Closed by NelsonGaldeman** 2018-02-14 18:18 UTC
